# Generated by Django 3.0.8 on 2021-03-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_auto_20210312_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='PromoSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slider/%Y/%m/%d')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_slide', to='shop.Product')),
                ('promo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promo.PromoSlider')),
            ],
        ),
        migrations.CreateModel(
            name='PromoBaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='promo/%Y/%m/%d')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_baner', to='shop.Product')),
            ],
        ),
    ]
