# Generated by Django 3.0.8 on 2021-03-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promobaner_promoslide_promoslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoslide',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promoslide',
            name='promo',
        ),
        migrations.DeleteModel(
            name='PromoBaner',
        ),
        migrations.DeleteModel(
            name='PromoSlide',
        ),
        migrations.DeleteModel(
            name='PromoSlider',
        ),
    ]
