# Generated by Django 3.0.8 on 2021-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='pricr',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_way',
            field=models.CharField(choices=[('FREE', 'Бесплатная доставка'), ('SELF', 'Саамовывоз'), ('PAID', 'Доставка с оплатной')], default='FREE', max_length=4),
        ),
    ]
